### PR TITLE
Change tpch validation to use `exec_sql_on_tables`

### LINKED ISSUE #65: TPCH queries 7,8,9, do not validate
Queries 7,8,9 in the TPCH benchmark are producing output with the wrong schema value for year columns:

### Query 7 output:
DF-Ray:
```
+-------------+-------------+--------+---------------+
| supp_nation | cust_nation | l_year | revenue       |
+-------------+-------------+--------+---------------+
| GERMANY     | IRAQ        | 1995.0 | 51735313.3570 |
| GERMANY     | IRAQ        | 1996.0 | 49844675.4588 |
| IRAQ        | GERMANY     | 1995.0 | 57157895.2556 |
| IRAQ        | GERMANY     | 1996.0 | 57172189.4415 |
+-------------+-------------+--------+---------------+
```

DataFusion 43.0.0
```
+-------------+-------------+--------+---------------+
| supp_nation | cust_nation | l_year | revenue       |
+-------------+-------------+--------+---------------+
| GERMANY     | IRAQ        | 1995   | 51735313.3570 |
| GERMANY     | IRAQ        | 1996   | 49844675.4588 |
| IRAQ        | GERMANY     | 1995   | 57157895.2556 |
| IRAQ        | GERMANY     | 1996   | 57172189.4415 |
+-------------+-------------+--------+---------------+
```

### PR DESCRIPTION
**Pull request by vmingchen**
Fixes https://github.com/apache/datafusion-ray/issues/65

`exec_sql_on_tables` is a util function added by this PR that uses DataFution without Ray to execute queries. This ensures the validation is using the same Rust version as the DataFusion-Ray avoiding validation failure caused by inconsistency between different versions of DataFusion and DataFusion-Python. With this change, all TPCH validations are passing regardless of versions.

Also, expose the `schema` of `RayDataFrame` to facilitate debugging.

Thank @robtandy for the idea; see https://github.com/apache/datafusion-ray/issues/65#issuecomment-2679094341

### CODE REVIEW

**Comment by robtandy** [comment]
@vmingchen, thank you!  This looks good to me!

cc @andygrove for approval

File: src/util.rs [hunk 1]
```diff
@@ -397,6 +402,52 @@ fn print_node(plan: &Arc<dyn ExecutionPlan>, indent: usize, output: &mut String)
     }
 }
 
+async fn exec_sql(query: String, tables: Vec<(String, String)>) -> PyResult<RecordBatch> {
+    let ctx = SessionContext::new();
+    for (name, path) in tables {
+        if path.ends_with(".parquet") {
```
Comment (andygrove) [inline src/util.rs]: It may be better to check if path is a file or directory rather than basing the logic on file extension.

For example, in my local setup, I have a directory named `customer.parquet` that contains multiple Parquet files.

**Review by andygrove — APPROVED** [review]
Thanks @vmingchen

File: src/util.rs (hunk 1 above)
Comment (vmingchen) [reply src/util.rs]: Thanks for pointing this out! I looked into it, and it turned out [`register_parquet` internally use `register_listing_table` as well](https://github.com/apache/datafusion/blob/fc2fbb3d6b3aded73f1b0902168e008e580c89c1/datafusion/core/src/execution/context/parquet.rs#L55-L61). The later is capable of register both a single file and a directory of files. So I have changed the function to use `register_listing_table` only in https://github.com/apache/datafusion-ray/pull/66/commits/b8e0c6b3c10321896f39e33dee94ea843d91505a; the new commit also adds a unit test to check that it is working for both file and directory and a doc pointing to the format of the URI.

Please take another look; thanks!

Comment (andygrove) [reply src/util.rs]: Thanks for updating that. LGTM.
